name: PR-$(System.PullRequest.PullRequestNumber)-$(Date:yyyyMMdd)$(Rev:.rr)

variables:
  # Don't download unneeded packages
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: 'true'
  # Improve performance by not sending telemetry
  - name: DOTNET_CLI_TELEMETRY_OPTOUT
    value: 'true'

trigger:
  batch: true
  branches:
    include:
      - master

jobs:
- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - template: templates/ci-general.yml

- job: macOS
  pool:
    vmImage: 'macOS-10.15'
  steps:
  - template: templates/ci-general.yml

- job: Linux
  pool:
    vmImage: 'Ubuntu-20.04'
  steps:
  - template: templates/ci-general.yml
